version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for poetry/pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    # no point in having more than 2 pull requests at a time as a rebase is always
    # necessary
    open-pull-requests-limit: 2
